source 'https://rubygems.org'

gem 'middleman'
gem 'middleman-blog'
gem 'middleman-syntax'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'builder'
gem 'duktape'
gem 'nokogiri'

#gem 'json'
#gem 'middleman', '~> 3.3.7'
#gem 'middleman-blog', '~> 3.5.3'
#gem 'middleman-deploy'
#gem 'middleman-syntax'
#gem 'webrick'
